### ISSUE TITLE
[PE-D][Tester D] unmatchable mark command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-2/tp#146] opened 2023-03-31 17:18 UTC
Mark command in the UG does not meet with the one provided by the app
![Picture13.png](https://raw.githubusercontent.com/shenchenzizoe/ped/main/files/2f48c2cb-6dcc-4540-9813-ae60b3e76afe.png)

![Picture12.png](https://raw.githubusercontent.com/shenchenzizoe/ped/main/files/539890af-190c-419f-aca2-e637bd101afb.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: shenchenzizoe/ped#5

**Comment by Beebeeoii** [comment] 2023-04-01 11:42
duplicate of #165

**Closed by Beebeeoii** 2023-04-01 11:42 UTC
