### ISSUE TITLE
[PE-D][Tester E] Help link redirection not updated to point to the current help guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-2/tp#133] opened 2023-03-31 16:40 UTC
![image.png](https://raw.githubusercontent.com/WesleyBLDC/ped/main/files/57620995-8509-4634-b7e5-eba70ff50a93.png)

Suggest to....

update the hyperlink in the code
update the UG to reflect the correct expected visual that the user will see

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: WesleyBLDC/ped#3

**Comment by Beebeeoii** [comment] 2023-04-01 11:49
duplicate of #138

**Closed by Beebeeoii** 2023-04-01 11:49 UTC
