### ISSUE TITLE
[PE-D][Tester E] 2nd image mismatch in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-2/tp#131] opened 2023-03-31 16:36 UTC
SImilar to the previous UG issue, mismatch in the current UI and UG.

![image.png](https://raw.githubusercontent.com/WesleyBLDC/ped/main/files/8f5b5d19-cd38-40bf-bdf3-6b1cce631e23.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: WesleyBLDC/ped#2

**Comment by Beebeeoii** [comment] 2023-04-01 11:51
duplicate of #174

**Closed by Beebeeoii** 2023-04-01 11:51 UTC
